name: Node.js CI

on:
  push:
    tags:
      - "v*.*"

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: "lts/*"
    - uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: true
    - run: pnpm build
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: dist/game2dx.user.js

permissions:
  contents: write
